# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipfs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nipfs.proto\"3\n\x06PBLink\x12\x0c\n\x04Hash\x18\x01 \x01(\x0c\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\r\n\x05Tsize\x18\x03 \x01(\x04\"5\n\x06PBNode\x12\x16\n\x05Links\x18\x02 \x03(\x0b\x32\x07.PBLink\x12\x13\n\x04\x44\x61ta\x18\x01 \x01(\x0b\x32\x05.Data\"\xfa\x01\n\x04\x44\x61ta\x12\x1c\n\x04Type\x18\x01 \x02(\x0e\x32\x0e.Data.DataType\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilesize\x18\x03 \x01(\x04\x12\x12\n\nblocksizes\x18\x04 \x03(\x04\x12\x10\n\x08hashType\x18\x05 \x01(\x04\x12\x0e\n\x06\x66\x61nout\x18\x06 \x01(\x04\x12\x0c\n\x04mode\x18\x07 \x01(\r\x12\x18\n\x05mtime\x18\x08 \x01(\x0b\x32\t.UnixTime\"V\n\x08\x44\x61taType\x12\x07\n\x03Raw\x10\x00\x12\r\n\tDirectory\x10\x01\x12\x08\n\x04\x46ile\x10\x02\x12\x0c\n\x08Metadata\x10\x03\x12\x0b\n\x07Symlink\x10\x04\x12\r\n\tHAMTShard\x10\x05\":\n\x08UnixTime\x12\x0f\n\x07Seconds\x18\x01 \x02(\x03\x12\x1d\n\x15\x46ractionalNanoseconds\x18\x02 \x01(\x07\"\x1c\n\x08Metadata\x12\x10\n\x08MimeType\x18\x01 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipfs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBLINK._serialized_start=14
  _PBLINK._serialized_end=65
  _PBNODE._serialized_start=67
  _PBNODE._serialized_end=120
  _DATA._serialized_start=123
  _DATA._serialized_end=373
  _DATA_DATATYPE._serialized_start=287
  _DATA_DATATYPE._serialized_end=373
  _UNIXTIME._serialized_start=375
  _UNIXTIME._serialized_end=433
  _METADATA._serialized_start=435
  _METADATA._serialized_end=463
# @@protoc_insertion_point(module_scope)